### PR TITLE
Better explorer appearance

### PR DESCRIPTION
**Pull request by shanberg**

### CODE REVIEW

**Comment by spmcbride1201** [comment]
Here's what the charts look like for me: image

**Comment by shanberg** [comment]
@spmcbride1201 I saw the same no-height issue until the chart updated with content. Are you seeing that happen at all?

**Comment by spmcbride1201** [comment]
@shanberg Nope, stays like this.

**Comment by spmcbride1201** [comment]
For the sake of time, maybe UIKit3's responsive flexbox classes might be helpful for the layout issues: https://getuikit.com/docs/flex#responsive

**Pull request merged**
