### PR TITLE
WIP 1041 Refactor Form SCSS

### LINKED ISSUE #1041: Refactor form-control from SCSS to styled-components
the form-control class is used by
- Functions Grid
- Go Routes Table Toolbar
- JVM Routes Table Toolbar
- Service Table Toolbar

### PR DESCRIPTION
**Pull request by kaitmore**
Resolves #1041 

## Proposed Changes

  - Factored out forms.scss into a global pattern `form_control`
  - Removed all references to the form_control classname
  - Deleted forms.scss

### CODE REVIEW

**Comment by spmcbride1201** [comment]
I'm going to add my comments one at a time because it's going to take hours to test this cross browser.

**Comment by spmcbride1201** [comment]
You're still importing the forms.scss file in index.scss, so build is failing

**Comment by spmcbride1201** [comment]
Regression on Safari 11
Old
image
New

image

**Comment by spmcbride1201** [comment]
IE11 on Windows 7 seems fine.

**Comment by kaitmore** [comment]
@spmcbride1201 Deleted any references to forms.scss, fixed Safari regression, and updated snapshots 👍🏼

**Pull request merged**
