### PR TITLE
658 add: webpack-dashboard plugin

### LINKED ISSUE #658: Implement Webpack Dashboard Tooling
Makes the console a bit more useful.
https://github.com/FormidableLabs/webpack-dashboard
Validate and document support for this:
https://github.com/FormidableLabs/electron-webpack-dashboard

### PR DESCRIPTION
**Pull request by karinakeen**
Resolve #658

### CODE REVIEW

**Comment by karinakeen** [comment]
@spmcbride1201 do you want me to research this further?

**Comment by spmcbride1201** [comment]
@karinakeen. Nope, unless you have strong feelings that you can get it working better, I think we can just close this out and chalk this up to getting you acquainted with the project's webpack configs. Feel free to close the PR and wipe the branch.

**Comment by karinakeen** [comment]
@spmcbride1201  Not sure if you already checked the tabs? 
screen shot 2017-10-25 at 12 46 54 am
screen shot 2017-10-25 at 12 47 04 am
screen shot 2017-10-25 at 12 47 17 am

**Comment by spmcbride1201** [comment]
@karinakeen - Nope, I guess I was missing something obvious. Let me look again.

**Pull request merged**
